added view for profile post list
markusviola/theparadigmblog pull request #15
Opened 2019-04-25 09:47 UTC by markusviola

closes #13

2019-04-26 05:18 UTC, andybit-okutama commented on resources/views/profile.blade.php
> +                <div class="text-muted">Posted on September 19, 2014</div>
User created at for the date

2019-04-26 05:18 UTC, andy1dx requested changes
Review

2019-04-26 08:36 UTC, hugh-n reviewed
Will wait for fix before making review.

2019-05-09 04:55 UTC, andy1dx approved these changes

2019-05-09 04:56 UTC, merged