added view for home post list
markusviola/theparadigmblog pull request #16
Opened 2019-04-25 09:47 UTC by markusviola

closes #14

2019-04-26 05:21 UTC, andybit-okutama commented on app/Http/Controllers/HomeController.php
> +        $posts = BlogPost::all();
Add the ordering by created date desc

2019-04-26 05:22 UTC, andybit-okutama commented on resources/views/home.blade.php
> +
delete not use code

2019-04-26 05:22 UTC, andy1dx requested changes
Please fix

2019-04-26 08:38 UTC, hugh-n reviewed
Andy has already commented so I will review after the fixes are made.

2019-05-09 04:57 UTC, andybit-okutama commented on app/Http/Controllers/HomeController.php
> +        $posts = BlogPost::all();
@markusviola  Make The order

2019-05-09 05:30 UTC, markusviola commented on resources/views/home.blade.php
> +
done

2019-05-09 05:30 UTC, markusviola commented on app/Http/Controllers/HomeController.php
> +        $posts = BlogPost::all();
done

2019-05-09 05:36 UTC, andy1dx approved these changes
LGTM

2019-05-09 05:36 UTC, merged